# Datenbankverbindung
spring.datasource.url=jdbc:postgresql://c7itisjfjj8ril.cluster-czrs8kj4isg7.us-east-1.rds.amazonaws.com:5432/d2rl3u3etmbokj
spring.datasource.username=u239s7foq1mg2u
spring.datasource.password=pbaa8f9c9c8f5202f2489c519d6208ba405d1251d420e222db71aa1bcb1eb7441
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Datenbankinitialisierung
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:db/init.sql

# JWT
jwt.secret=dein-geheimer-schluessel-mindestens-256bit-lang-sicher-1234567890
jwt.expiration-hours=8

# Ticketpreise
ticket.preis.standard=15.00
ticket.preis.vip=17.00
ticket.preis.ermaessigt=8.00

# Verzehrgebuehr
kasse.verzehr.enabled=false
kasse.verzehr.preis=5.00

# Veranstaltung
veranstaltung.max-teilnehmer=200

# App
server.port=8080
spring.application.name=party-manager
spring.jpa.open-in-view=false
